/**
 * contextDetectorsHelpers.ts — Static data constants for context detection.
 *
 * Extracted from contextDetectors.ts to keep each file under 300 lines.
 */

export const FRAMEWORK_SIGNATURES: Record<string, { deps: string[]; label: string }> = {
  next: { deps: ['next'], label: 'Next.js' },
  nuxt: { deps: ['nuxt', 'nuxt3'], label: 'Nuxt' },
  remix: { deps: ['@remix-run/node', '@remix-run/react'], label: 'Remix' },
  astro: { deps: ['astro'], label: 'Astro' },
  sveltekit: { deps: ['@sveltejs/kit'], label: 'SvelteKit' },
  gatsby: { deps: ['gatsby'], label: 'Gatsby' },
  react: { deps: ['react'], label: 'React' },
  vue: { deps: ['vue'], label: 'Vue' },
  svelte: { deps: ['svelte'], label: 'Svelte' },
  angular: { deps: ['@angular/core'], label: 'Angular' },
  express: { deps: ['express'], label: 'Express' },
  fastify: { deps: ['fastify'], label: 'Fastify' },
  hono: { deps: ['hono'], label: 'Hono' },
  nestjs: { deps: ['@nestjs/core'], label: 'NestJS' },
  electron: { deps: ['electron'], label: 'Electron' },
  tauri: { deps: ['@tauri-apps/api'], label: 'Tauri' },
  django: { deps: ['django', 'Django'], label: 'Django' },
  flask: { deps: ['flask', 'Flask'], label: 'Flask' },
  fastapi: { deps: ['fastapi'], label: 'FastAPI' },
  rails: { deps: ['rails'], label: 'Ruby on Rails' },
};

export const TEST_FRAMEWORKS: Record<string, string[]> = {
  vitest: ['vitest'],
  jest: ['jest', '@jest/core'],
  mocha: ['mocha'],
  ava: ['ava'],
  tap: ['tap'],
  pytest: ['pytest'],
  unittest: [],
  rspec: ['rspec'],
  'cargo test': [],
  'go test': [],
};

export const DIR_PURPOSES: Record<string, string> = {
  src: 'Source code',
  lib: 'Library code',
  app: 'Application code (may contain routes/pages)',
  pages: 'Page routes',
  components: 'UI components',
  hooks: 'Custom hooks',
  utils: 'Utility functions',
  helpers: 'Helper functions',
  types: 'Type definitions',
  models: 'Data models',
  services: 'Service layer',
  api: 'API routes or handlers',
  routes: 'Route definitions',
  middleware: 'Middleware functions',
  controllers: 'Controller layer',
  views: 'View templates',
  templates: 'Template files',
  static: 'Static assets',
  public: 'Public assets (served directly)',
  assets: 'Assets (images, fonts, etc.)',
  styles: 'Stylesheets',
  css: 'CSS files',
  config: 'Configuration files',
  scripts: 'Build/utility scripts',
  test: 'Test files',
  tests: 'Test files',
  __tests__: 'Test files (Jest convention)',
  spec: 'Test specifications',
  e2e: 'End-to-end tests',
  docs: 'Documentation',
  doc: 'Documentation',
  migrations: 'Database migrations',
  prisma: 'Prisma schema and migrations',
  db: 'Database configuration',
  locales: 'Internationalization files',
  i18n: 'Internationalization',
  plugins: 'Plugin modules',
  extensions: 'Extension modules',
  '.github': 'GitHub workflows and config',
  '.vscode': 'VS Code workspace settings',
  dist: 'Build output',
  build: 'Build output',
  out: 'Build output',
  node_modules: 'npm dependencies (auto-managed)',
  vendor: 'Vendored dependencies',
  packages: 'Monorepo packages',
  apps: 'Monorepo applications',
  crates: 'Rust workspace crates',
};

export const CONFIG_FILES = [
  'tsconfig.json',
  'jsconfig.json',
  '.eslintrc',
  '.eslintrc.js',
  '.eslintrc.json',
  '.eslintrc.yml',
  'eslint.config.js',
  'eslint.config.mjs',
  '.prettierrc',
  '.prettierrc.js',
  '.prettierrc.json',
  'prettier.config.js',
  'vite.config.ts',
  'vite.config.js',
  'vite.config.mts',
  'webpack.config.js',
  'webpack.config.ts',
  'rollup.config.js',
  'rollup.config.mjs',
  'esbuild.config.js',
  'esbuild.config.mjs',
  'turbo.json',
  'nx.json',
  'lerna.json',
  '.babelrc',
  'babel.config.js',
  'babel.config.json',
  'tailwind.config.js',
  'tailwind.config.ts',
  'tailwind.config.mjs',
  'postcss.config.js',
  'postcss.config.cjs',
  'jest.config.js',
  'jest.config.ts',
  'jest.config.json',
  'vitest.config.ts',
  'vitest.config.js',
  '.env',
  '.env.example',
  '.env.local',
  'docker-compose.yml',
  'docker-compose.yaml',
  'Dockerfile',
  'Makefile',
  '.github/workflows',
  'vercel.json',
  'netlify.toml',
  'electron-builder.yml',
  'electron-builder.json5',
  'pyproject.toml',
  'setup.py',
  'setup.cfg',
  'Cargo.toml',
  'go.mod',
  'Gemfile',
  '.gitignore',
];

export const MONOREPO_MARKERS = ['pnpm-workspace.yaml', 'lerna.json', 'turbo.json', 'nx.json'];

export const DEPENDENCY_PATTERNS = [
  {
    label: 'Tailwind CSS',
    matches: (allDeps: Record<string, string>) => Boolean(allDeps['tailwindcss']),
  },
  {
    label: 'Prisma ORM',
    matches: (allDeps: Record<string, string>) =>
      Boolean(allDeps['prisma'] || allDeps['@prisma/client']),
  },
  {
    label: 'Drizzle ORM',
    matches: (allDeps: Record<string, string>) => Boolean(allDeps['drizzle-orm']),
  },
  {
    label: 'tRPC',
    matches: (allDeps: Record<string, string>) =>
      Boolean(allDeps['trpc'] || allDeps['@trpc/server']),
  },
  {
    label: 'GraphQL',
    matches: (allDeps: Record<string, string>) =>
      Boolean(allDeps['graphql'] || allDeps['@apollo/client'] || allDeps['@graphql-tools/schema']),
  },
  {
    label: 'Docker',
    matches: (allDeps: Record<string, string>, keyConfigs: string[]) =>
      Boolean(allDeps['docker-compose'] || keyConfigs.some((c) => c.startsWith('docker'))),
  },
  {
    label: 'Electron app',
    matches: (allDeps: Record<string, string>) => Boolean(allDeps['electron']),
  },
];
