#!/usr/bin/env node
// Wave 92 Phase 4 — lockfile:check script.
//
// Validates that the current package-lock.json was produced by `lockfile:sync`
// by comparing its SHA-256 against the hash recorded in .lockfile-sync.marker.
//
// Exit codes:
//   0 — marker present + hash matches (or bypass env is set)
//   1 — marker missing, or hash mismatch; stderr names the fix command
//
// Advisory bypass: set LOCKFILE_SYNC_GUARD_BYPASS=1 to exit 0 unconditionally.
// Use for the rare legitimate case (e.g. registry mirror rewrite, CI overrides).
//
// Invoked via: npm run lockfile:check

import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = resolve(fileURLToPath(import.meta.url), '..');
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const LOCK_PATH = resolve(REPO_ROOT, 'package-lock.json');
const MARKER_PATH = resolve(REPO_ROOT, '.lockfile-sync.marker');

function sha256File(p) {
  const h = createHash('sha256');
  h.update(readFileSync(p));
  return h.digest('hex');
}

function fail(msg) {
  process.stderr.write(`[lockfile:check] ERROR: ${msg}\n  Run \`npm run lockfile:sync\` to regenerate.\n`);
  process.exit(1);
}

function readMarker() {
  try {
    const marker = JSON.parse(readFileSync(MARKER_PATH, 'utf8'));
    if (typeof marker.lockfileSha256 !== 'string') {
      fail('.lockfile-sync.marker is missing the lockfileSha256 field.');
    }
    return marker;
  } catch (err) {
    fail(`could not parse .lockfile-sync.marker: ${err.message}`);
  }
}

function checkShaMatch(marker) {
  const actualSha = sha256File(LOCK_PATH);
  if (actualSha !== marker.lockfileSha256) {
    process.stderr.write(
      '[lockfile:check] ERROR: package-lock.json has changed since .lockfile-sync.marker was written.\n' +
        `  marker sha256:  ${marker.lockfileSha256}\n` +
        `  current sha256: ${actualSha}\n` +
        '  This means package-lock.json was modified outside of `npm run lockfile:sync`.\n' +
        '  Run `npm run lockfile:sync` to regenerate the lockfile and update the marker.\n',
    );
    process.exit(1);
  }
}

function main() {
  if (process.env.LOCKFILE_SYNC_GUARD_BYPASS === '1') {
    process.exit(0);
  }
  if (!existsSync(LOCK_PATH)) {
    fail('package-lock.json not found at repo root.');
  }
  if (!existsSync(MARKER_PATH)) {
    fail(
      '.lockfile-sync.marker is missing.\n' +
        '  package-lock.json may not have been generated by `npm run lockfile:sync`.',
    );
  }
  const marker = readMarker();
  checkShaMatch(marker);
  process.exit(0);
}

main();
