/**
 * pinnedContext.ts — Shared types for the pinned context primitive (Wave 25).
 *
 * Used by main process (store, IPC handlers), renderer (UI components, hooks),
 * and preload (bridge). Kept in @shared so all three processes can import it.
 */

export type PinnedContextType =
  | 'research-artifact'
  | 'user-file'
  | 'symbol-neighborhood'
  | 'graph-blast-radius';

export interface PinnedContextItem {
  /** UUID v4 — generated by pinnedContextStore.add() */
  id: string;
  type: PinnedContextType;
  /** File path, URL, or "library@version" string for research artifacts */
  source: string;
  /** Short display label shown in collapsed card header */
  title: string;
  /** Actual pinned text — token-capped before storage */
  content: string;
  /** Estimated token count for budget accounting */
  tokens: number;
  /** Epoch milliseconds when the item was pinned */
  addedAt: number;
  /**
   * Soft-hide within session — still present in the array and counts toward
   * undo, but not included in the rendered list or context packet by default.
   */
  dismissed?: boolean;
}
